# Generated by Django 3.1.1 on 2020-09-27 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageandroid',
            name='angle',
            field=models.CharField(default=242, max_length=30),
        ),
        migrations.AddField(
            model_name='imageandroid',
            name='latitude',
            field=models.CharField(default=242, max_length=30),
        ),
        migrations.AddField(
            model_name='imageandroid',
            name='longitude',
            field=models.CharField(default=242, max_length=30),
        ),
    ]
